config/routes.rb
Chalkboard::Application.routes.draw do
  devise_for :users
  resources :books

  root "home#show"
  get "home/show" => "home#show", as: "home"

  get "search/query"
  get "search/index"

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  searchable do
    text :estc_cit_number, :main_title

    string :estc_cit_number
    string :author_name
    string :author_titles_etc
    string :author_dates
    string :corporate_author
    string :corporate_author_specific
    string :main_title
    string :continuation_of_title
    string :publication_place
    string :imprint
    string :imprint_date
    string :pagination
    string :illustrations
    string :format
    string :pub_year
    string :bibliographic_citations

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # override devise's email method to allow the app to
  # send emails as a background process and redirect
  # new registrants back to the home page before their
  # email is sent
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Method to whitelist (accept known good entity) 
  # name parameter on all controllers
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:estc_cit_number, :author_name, :author_titles_etc, :author_dates, :corporate_author, :corporate_author_specific, :main_title, :continuation_of_title, :publication_place, :imprint, :imprint_date, :pagination, :illustrations, :format, :pub_year, :bibliographic_citations)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search = Book.search do
      fulltext params[:q]
    end
    @search_results = retrieve_search_results(search)
  end


  def retrieve_search_results(search_instance)
    results = search_instance.results.map do |book|
      {main_title: book.main_title,
        estc_id: book.estc_cit_number}
    end
    return results
  end


  def query
    # As users type into the typeahead box, the [:q] param
    # will be updated so it includes the user-supplied text,
    # and the search object will be updated to contain all 
    # matching records
    search = Book.search do
      fulltext params[:q] # Full text search
    end

    respond_to do |format|
      format.json do

        # Create an array from the search results.
        results = search.results.map do |book|
          # Each element will be a hash containing 
          # the main title and estc id fields for the record
          { main_title: book.main_title,
            estc_id: book.estc_cit_number }
        end
        render json: results
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estc_cit_number %><br>
    <%= f.text_field :estc_cit_number %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br>
    <%= f.text_field :author_name %>
  </div>
  <div class="field">
    <%= f.label :author_titles_etc %><br>
    <%= f.text_field :author_titles_etc %>
  </div>
  <div class="field">
    <%= f.label :author_dates %><br>
    <%= f.text_field :author_dates %>
  </div>
  <div class="field">
    <%= f.label :corporate_author %><br>
    <%= f.text_field :corporate_author %>
  </div>
  <div class="field">
    <%= f.label :corporate_author_specific %><br>
    <%= f.text_field :corporate_author_specific %>
  </div>
  <div class="field">
    <%= f.label :main_title %><br>
    <%= f.text_field :main_title %>
  </div>
  <div class="field">
    <%= f.label :continuation_of_title %><br>
    <%= f.text_field :continuation_of_title %>
  </div>
  <div class="field">
    <%= f.label :publication_place %><br>
    <%= f.text_field :publication_place %>
  </div>
  <div class="field">
    <%= f.label :imprint %><br>
    <%= f.text_field :imprint %>
  </div>
  <div class="field">
    <%= f.label :imprint_date %><br>
    <%= f.text_field :imprint_date %>
  </div>
  <div class="field">
    <%= f.label :pagination %><br>
    <%= f.text_field :pagination %>
  </div>
  <div class="field">
    <%= f.label :illustrations %><br>
    <%= f.text_field :illustrations %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
  <div class="field">
    <%= f.label :pub_year %><br>
    <%= f.text_field :pub_year %>
  </div>
  <div class="field">
    <%= f.label :bibliographic_citations %><br>
    <%= f.text_field :bibliographic_citations %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">
  <div class="col-md-12">
    <fieldset>
      <legend>Matching Records</legend>
      <ul>
        <% @books.each do |book| %>
          <div class="book-result">
            <%= link_to book.estc_cit_number, book %>
            <%= book.main_title %>
            <% if book.author_name != "NULL" %>
              <%= book.author_name %>
            <% end %>
            <%= book.pub_year %>
          </div>
          <br>
        <% end %>

      </ul>

      <%= link_to 'New Book', new_book_path %>
    </fieldset>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Estc cit number:</strong>
      <%= @book.estc_cit_number %>
    </p>

    <p>
      <strong>Author name:</strong>
      <%= @book.author_name %>
    </p>

    <p>
      <strong>Author titles etc:</strong>
      <%= @book.author_titles_etc %>
    </p>

    <p>
      <strong>Author dates:</strong>
      <%= @book.author_dates %>
    </p>

    <p>
      <strong>Corporate author:</strong>
      <%= @book.corporate_author %>
    </p>

    <p>
      <strong>Corporate author specific:</strong>
      <%= @book.corporate_author_specific %>
    </p>

    <p>
      <strong>Main title:</strong>
      <%= @book.main_title %>
    </p>

    <p>
      <strong>Continuation of title:</strong>
      <%= @book.continuation_of_title %>
    </p>

    <p>
      <strong>Publication place:</strong>
      <%= @book.publication_place %>
    </p>

    <p>
      <strong>Imprint:</strong>
      <%= @book.imprint %>
    </p>

    <p>
      <strong>Imprint date:</strong>
      <%= @book.imprint_date %>
    </p>

    <p>
      <strong>Pagination:</strong>
      <%= @book.pagination %>
    </p>

    <p>
      <strong>Illustrations:</strong>
      <%= @book.illustrations %>
    </p>

    <p>
      <strong>Format:</strong>
      <%= @book.format %>
    </p>

    <p>
      <strong>Pub year:</strong>
      <%= @book.pub_year %>
    </p>

    <p>
      <strong>Bibliographic citations:</strong>
      <%= @book.bibliographic_citations %>
    </p>

    <%= link_to 'Edit', edit_book_path(@book) %> |
    <%= link_to 'Back', books_path %>
  </div>
</div>

app/views/home/show.html.erb
<!-- append view css to head -->
<% content_for :header do -%>
<% end -%>

<div id="headerwrap">
  <div class="container">
    <div class="row centered-text">
      <div class="col-lg-8 col-lg-offset-2">
        <h1>ESTC <b>Chalkboard</b></h1>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </div><!-- row -->

    <div class="row" id="search-row">
      
      <!-- Search Box -->
      <div id="search-box-background" class="centered">
        <%= form_tag search_index_path, :method => :get do %>
          <div id="typeahead-container" class="search">
            <%= text_field_tag :q, params[:q], :class => "typeahead", :id => "typeahead-field", :type => "text", :placeholder => "Search for a record" %>
            <i class="fa fa-search" id="search-glass"></i>
          </div>
          
          <!-- Submit Button -->
          <%= submit_tag "Search", :name => nil, :class => "btn btn-primary", :id=> "submit-search" %>
        
        <% end %>
      </div>
    </div>
  </div><!-- container -->
</div>

<div class="container w">
  <div class="row centered-text">
    <div class="col-lg-4">
      <i class="fa fa-bar-chart"></i>
      <h4>LOREM</h4>
      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
    </div><!-- col-lg-4 -->

    <div class="col-lg-4">
      <i class="fa fa-edit"></i>
      <h4>LOREM</h4>
      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
    </div><!-- col-lg-4 -->

    <div class="col-lg-4">
      <i class="fa fa-info"></i>
      <h4>LOREM</h4>
      <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even believable.</p>
    </div><!-- col-lg-4 -->
  </div><!-- row -->
</div><!-- container -->

app/views/layouts/_header.html.erb
<!-- Navigation -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CHALKB<i class="fa fa-circle"></i>ARD</a>
    </div>
    
    <div class="navbar-collapse collapse">
 
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "HOME", root_path %>
          </li>
          <!-- Link to user's profile -->
          <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to current_user.name.upcase, edit_user_registration_path %>
          </li>
          <li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %>
          </li>
          
        <% else %>
          <li class="<%= 'active' if current_page?(root_path) %>" ><%= link_to "HOME", root_path %></li>
          <li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to 'LOGIN', new_user_session_path %></li>
          <li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to 'SIGN UP', new_user_registration_path %></li>
        <% end %>
      </ul>

    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chalkboard</title>
  <!-- retrieve view-specific css if any -->
  <%= yield(:header) if @content_for_header %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<body>
  <%= render 'layouts/header' %>
  <div class="page-content">
    <div id="messages">
      <%= render 'layouts/messages' %>
    </div>
    <div class="<%='container' unless current_page?(root_path) %>">
      <div class="<%='page-content' unless current_page?(root_path) %>">
        <%= yield %>
      </div>
    </div>
  </div>
</body>

app/views/search/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="page-content">
      <% @search_results.each do |result| %>
        <p> <%= result[:main_title] %> </p>
      <% end %>
    </div>
  </div>
</div>